#spring.application.name=config-client
#spring.cloud.config.label=master
#spring.cloud.config.profile=dev
#spring.cloud.config.uri= http://localhost:8888/
#server.port=8881

spring:
  application:
    name: config-client
  cloud:
    config:
      #指明远程仓库的分支
      label: master
      #dev开发环境配置文件
      #test测试环境
      #pro正式环境
      profile: dev
      #指明配置服务中心的网址
      #uri: http://localhost:8888/
      discovery: 
        #是从配置中心读取文件
        enable: true
        #配置中心的servieId，即服务名
        serviceId: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
server:
  port: 8881

eureka:
  instance:
    hostname: localhost
    instance-id: http://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
      
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
# spring.rabbitmq.username=
# spring.rabbitmq.password=
