server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: Tiger
    driverClassName : com.mysql.jdbc.Driver
    poolName : hikariCP
    maximumPoolSize : 25 
    minimumIdle : 3
    connectionTimeout : 30000
    idleTimeout : 30000
    pool-prepared-statements : true
    max-open-prepared-statements : 250
#  velocity:
#    resource-loader-path: classpath:/public/views/
#    toolbox-config-location: /toolbox.xml
#    cache: false
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    properties:
#      userdirective: com.baidu.fis.velocity.directive.Html, com.baidu.fis.velocity.directive.Head, com.baidu.fis.velocity.directive.Body, com.baidu.fis.velocity.directive.Require, com.baidu.fis.velocity.directive.Script, com.baidu.fis.velocity.directive.Style, com.baidu.fis.velocity.directive.Uri, com.baidu.fis.velocity.directive.Widget, com.baidu.fis.velocity.directive.Block, com.baidu.fis.velocity.directive.Extends
  jooq:
    sql-dialect: MYSQL
  output:
    ansi:
      enabled: DETECT
  profiles:
    active: dev
      
logging:
  level: 
    com.it: debug
    
swagger:
  enabled: true
# 指定环境为dev
#spring.profiles.active=dev

