server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: Tiger
    driverClassName : com.mysql.jdbc.Driver
    poolName : hikariCP
    maximumPoolSize : 25 
    minimumIdle : 3
    connectionTimeout : 30000
    idleTimeout : 30000
    pool-prepared-statements : true
    max-open-prepared-statements : 250
  redis: 
    database: 1
    hostName: 192.168.203.132
    password: 
    port: 6379
    timeout: 0  
    max-active: 8  
    max-wait: -1  
    max-idle: 8  
    min-idle: 0
  jooq:
    sql-dialect: MYSQL
  output:
    ansi:
      enabled: DETECT
  rabbitmq:
    host: 192.168.203.132
    port: 5672
    username: mryinying
    password: 654321
    publisher-confirms: true
    virtual-host: /

logging:
  level: 
    com.it: debug
    
swagger:
  enabled: true
# 指定环境为dev
#spring.profiles.active=dev
#    spring.output.ansi.enabled

