server:
  port: 8888

spring:
  profiles:
    active: test  #指定开发环境 多环境配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: Tiger
    driverClassName : com.mysql.jdbc.Driver
    poolName : hikariCP
    maximumPoolSize : 25 
    minimumIdle : 3
    connectionTimeout : 30000
    idleTimeout : 30000
    pool-prepared-statements : true
    max-open-prepared-statements : 250
  jooq:
    sql-dialect: MYSQL
  output:
    ansi:
      enabled: DETECT
      
logging:
  level: 
    com.it: debug
    
blog:
  value: {random.value}
  number: ${random.int}
  
  
  
#@PropertySource(value="classpath:my.yml",encoding="utf-8")
## 随机字符串
#.blog.value=${random.value}
## 随机int
#.blog.number=${random.int}
## 随机long
#.blog.bignumber=${random.long}
## 10以内的随机数
#.blog.test1=${random.int(10)}
## 1-20的随机数
#.blog.test2=${random.int[1,20]}